### PR TITLE
Updated Elasticsearch Versions

### PR DESCRIPTION
**Pull request by lefte**
* Updated versions 6, 7, and 8 to the latest supported Bitnami tags
* Added ES 8.3-8.15 to the supported version matrix
* Corrected bitnami ES config tests and silenced curl progress bars
  * Bitnami stopped adding data node customization after 6.8.21

### Bare minimum self-checks

> [What do you think of a person who only does the bare minimum?](https://getyarn.io/yarn-clip/dcf80710-425e-478b-bde1-c107bd11e849)

- [x] I've updated this PR with the latest code from `main`
- [x] I've done a cursory QA pass of my code locally
- [x] I've ensured all automated status check and tests pass
- [ ] I've [connected this PR to an issue](https://help.zenhub.com/support/solutions/articles/43000010350-connecting-pull-requests-to-github-issues)

### Pieces of flare

- [x] I've written a unit or functional test for my code
- [x] I've updated relevant documentation it my code changes it
- [ ] I've updated this repo's README if my code changes it
- [ ] I've updated this repo's CHANGELOG with my change unless its a trivial change (like updating a typo in the docs)

### Finally

- [x] I've [requested a review](https://help.github.com/en/articles/requesting-a-pull-request-review) with relevant people

If you have any issues or need help please join the `#contributors` channel in the [Lando slack](https://www.launchpass.com/devwithlando) and someone will gladly help you out!

You can also check out the [coder guide](https://docs.lando.dev/contrib/coder.html).

### CODE REVIEW

**Comment by lefte** [comment]
hmm, my local test returns this:
```bash
# Should portforward for custom
lando info -s custom | grep "external_connection" | grep --regexp="port: '\d*'"
    external_connection: { host: '127.0.0.1', port: '61313' },
```
but the Leia test is failing with:
```
  1) elasticsearch-example
       should portforward for custom:
     Error: CODE: 1
STDOUT: 
STDERR: 
      at /tmp/leia/f23dd5036d11ea8e03a0218afb01cc62d1cc4207/elasticsearch-example.leia.js:98:14
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
🤔

**Comment by reynoldsalec** [comment]
@lefte have you tried the original `lando info -s custom | grep "not forwarded" || echo $? | grep 1`? Seems like there might be a reason that was chosen as the test, although would be good to know why.

Could also just try a diagnostic command in the test run (like running `lando info -s custom`) to see what's different...guessing it might be a Linux vs. Mac difference. Note you may have to re-run the GitHub Action test using debug mode to see FULL output (which may have more helpful diagnostic info).

**Comment by lefte** [comment]
> @lefte have you tried the original `lando info -s custom | grep "not forwarded" || echo $? | grep 1`? Seems like there might be a reason that was chosen as the test, although would be good to know why.
> 
> Could also just try a diagnostic command in the test run (like running `lando info -s custom`) to see what's different...guessing it might be a Linux vs. Mac difference. Note you may have to re-run the GitHub Action test using debug mode to see FULL output (which may have more helpful diagnostic info).

output of `lando info -s custom` for me locally is:
```bash
[ { service: 'custom',
    urls: [],
    type: 'elasticsearch',
    healthy: true,
    environment:
     { ELASTICSEARCH_IS_DEDICATED_NODE: 'no',
       ELASTICSEARCH_CLUSTER_NAME: 'bespin',
       ELASTICSEARCH_NODE_NAME: 'lando',
       ELASTICSEARCH_PORT_NUMBER: 9200,
       ELASTICSEARCH_PLUGINS: 'analysis-icu',
       ELASTICSEARCH_HEAP_SIZE: '1026m',
       LANDO_NEEDS_EXEC: 'DOEEET' },
    internal_connection: { host: 'custom', port: '9200' },
    external_connection: { host: '127.0.0.1', port: '62067' },
    healthcheck: 'curl -XGET localhost:9200',
    config: { server: 'config/custom.yml' },
    version: '7',
    meUser: 'www-data',
    hasCerts: false,
    api: 3,
    hostnames: [ 'custom.landoelasticsearch.internal' ] } ]
```
which is then piped to grep the external_connection line, and then further piped to regex that it returns a number.. I'm adding back in the original OR clause as well, to test.

**Comment by lefte** [comment]
@reynoldsalec all passing green now, I think it's been resolved - just refactored the actual test to look for a specific port instead of the grep with regexp ✅

**Comment by lefte** [comment]
> Sweet that makes sense @lefte and seems like a more exact test anyway.
> 
> I think the last thing is to add a CHANGELOG entry (make sure to merge in the main changes...I just put in the default format header for that) and update the `index.md` in the docs to show the new available versions, then should be good!

Last question -- do I need to bump the version number in `package.json` to `1.2.0` as well? Or is there a release process that does that?

**Comment by lefte** [comment]
Final update with corrected changelog formatting. Thanks again, guys!

**Comment by reynoldsalec** [comment]
Thanks to you @lefte!

**Pull request merged**
