### PR TITLE
Unlock elasticsearch 7.17, 8.1, 8.2, 8

### PR DESCRIPTION
**Pull request by rabauss**
I'm not sure if we need a pinPair for v8 too - can someone help?

### CODE REVIEW

**Comment by reynoldsalec** [comment]
Yes, you'll want to pin pair 8, looks like `bitnami/elasticsearch:8.2.3-debian-11-r4` is the most recent version right now on Docker Hub, so I'd start with that.

Other than that, you'll want to copy the `examples/7.x` directory as `8.x` and adapt it to test ES8. LMK if you need help with that, but _should_ be pretty much copy/paste :)

**Comment by rabauss** [comment]
But there is also an exisiting tag `bitnami/elasticsearch:8` - why pinning it?

**Comment by reynoldsalec** [comment]
@rabauss I know @pirog has been bitten in the past by allowing a floating pin...it's a real pain when a minor version upgrade does something unexpected and you start hearing from all the users about it. Hence the more tightly pinned versions for all the other ES versions.

**Comment by rabauss** [comment]
@reynoldsalec okay, I added  pin pair + test for elasticsearch 8

**Comment by reynoldsalec** [comment]
Thanks @rabauss!

**Pull request merged**
